### ISSUE TITLE
RuntimeError `ActiveRecord::SessionStore` is extracted out of Rails into a gem since version 1.1.3

### ISSUE THREAD

**Issue by javinto** [rails/activerecord-session_store#145]
Just upgraded to version 1.1.3 of this gem and bump into:

```
../config/initializers/session_store.rb:8:in `<main>'
.../ruby-2.5.1@rails5/gems/railties-5.2.3/lib/rails/application/configuration.rb:209:in `session_store'
.../ruby-2.5.1@rails5/gems/railties-5.2.3/lib/rails/application/configuration.rb:212:in `rescue in session_store': `ActiveRecord::SessionStore` is extracted out of Rails into a gem. Please add `activerecord-session_store` to your Gemfile to use it. (RuntimeError)
```

Version 1.1.2 is working well. I'm running Rails 5.2.3 on Ruby 2.5.1. 

I have  a config/initializers/session.rb file with:
`Rails.application.config.session_store :active_record_store`

**Comment by javinto** [comment]
After upgrading to Rails 6 and several gems the error disappeared
