### ISSUE TITLE
Getting: No such middleware to insert after: ActionDispatch::Session::CookieStore (RuntimeError)

### ISSUE THREAD

**Issue by jocko-wowza** [rails/activerecord-session_store#158]
I've followed the instructions from the README, and I'm getting this exception during startup, can anyone help identify why this is happening.  Googling for the error returns nothing.

```
! Unable to load application: RuntimeError: No such middleware to insert after: ActionDispatch::Session::CookieStore
Traceback (most recent call last):
	38: from bin/puma:31:in `<main>'
	37: from bin/puma:31:in `load'
	36: from /vendor/bundle/ruby/2.6.0/gems/puma-3.7.1/bin/puma:10:in `<top (required)>'
	35: from /vendor/bundle/ruby/2.6.0/gems/puma-3.7.1/lib/puma/cli.rb:77:in `run'
	34: from /vendor/bundle/ruby/2.6.0/gems/puma-3.7.1/lib/puma/launcher.rb:171:in `run'
	33: from /vendor/bundle/ruby/2.6.0/gems/puma-3.7.1/lib/puma/single.rb:87:in `run'
	32: from /vendor/bundle/ruby/2.6.0/gems/puma-3.7.1/lib/puma/runner.rb:138:in `load_and_bind'
	31: from /vendor/bundle/ruby/2.6.0/gems/puma-3.7.1/lib/puma/configuration.rb:250:in `app'
	30: from /vendor/bundle/ruby/2.6.0/gems/puma-3.7.1/lib/puma/configuration.rb:323:in `load_rackup'
	29: from /vendor/bundle/ruby/2.6.0/gems/rack-2.2.2/lib/rack/builder.rb:66:in `parse_file'
	28: from /vendor/bundle/ruby/2.6.0/gems/rack-2.2.2/lib/rack/builder.rb:105:in `load_file'
	27: from /vendor/bundle/ruby/2.6.0/gems/rack-2.2.2/lib/rack/builder.rb:116:in `new_from_string'
	26: from /vendor/bundle/ruby/2.6.0/gems/rack-2.2.2/lib/rack/builder.rb:116:in `eval'
	25: from config.ru:3:in `block in <main>'
	24: from config.ru:3:in `require'
	23: from /usr/src/app/cloud_ux/config/environment.rb:5:in `<top (required)>'
	22: from /vendor/bundle/ruby/2.6.0/gems/railties-5.2.4.3/lib/rails/application.rb:361:in `initialize!'
	21: from /vendor/bundle/ruby/2.6.0/gems/railties-5.2.4.3/lib/rails/initializable.rb:60:in `run_initializers'
	20: from /usr/local/lib/ruby/2.6.0/tsort.rb:205:in `tsort_each'
	19: from /usr/local/lib/ruby/2.6.0/tsort.rb:226:in `tsort_each'
	18: from /usr/local/lib/ruby/2.6.0/tsort.rb:347:in `each_strongly_connected_component'
	17: from /usr/local/lib/ruby/2.6.0/tsort.rb:347:in `call'
	16: from /usr/local/lib/ruby/2.6.0/tsort.rb:347:in `each'
	15: from /usr/local/lib/ruby/2.6.0/tsort.rb:349:in `block in each_strongly_connected_component'
	14: from /usr/local/lib/ruby/2.6.0/tsort.rb:431:in `each_strongly_connected_component_from'
	13: from /usr/local/lib/ruby/2.6.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
	12: from /usr/local/lib/ruby/2.6.0/tsort.rb:228:in `block in tsort_each'
	11: from /vendor/bundle/ruby/2.6.0/gems/railties-5.2.4.3/lib/rails/initializable.rb:61:in `block in run_initializers'
	10: from /vendor/bundle/ruby/2.6.0/gems/railties-5.2.4.3/lib/rails/initializable.rb:32:in `run'
	 9: from /vendor/bundle/ruby/2.6.0/gems/railties-5.2.4.3/lib/rails/initializable.rb:32:in `instance_exec'
	 8: from /vendor/bundle/ruby/2.6.0/gems/railties-5.2.4.3/lib/rails/application/finisher.rb:47:in `block in <module:Finisher>'
	 7: from /vendor/bundle/ruby/2.6.0/gems/railties-5.2.4.3/lib/rails/engine.rb:506:in `app'
	 6: from /vendor/bundle/ruby/2.6.0/gems/railties-5.2.4.3/lib/rails/engine.rb:506:in `synchronize'
	 5: from /vendor/bundle/ruby/2.6.0/gems/railties-5.2.4.3/lib/rails/engine.rb:509:in `block in app'
	 4: from /vendor/bundle/ruby/2.6.0/gems/railties-5.2.4.3/lib/rails/configuration.rb:70:in `merge_into'
	 3: from /vendor/bundle/ruby/2.6.0/gems/railties-5.2.4.3/lib/rails/configuration.rb:70:in `each'
	 2: from /vendor/bundle/ruby/2.6.0/gems/railties-5.2.4.3/lib/rails/configuration.rb:71:in `block in merge_into'
	 1: from /vendor/bundle/ruby/2.6.0/gems/actionpack-5.2.4.3/lib/action_dispatch/middleware/stack.rb:82:in `insert_after'
/vendor/bundle/ruby/2.6.0/gems/actionpack-5.2.4.3/lib/action_dispatch/middleware/stack.rb:108:in `assert_index': No such middleware to insert after: ActionDispatch::Session::CookieStore (RuntimeError)
```

GemFile:
```
source 'http://rubygems.org'

# First because it's the most important.
gem 'rails', '5.2.4.3'

### NOTE: Try to keep these in alphabetical order, unless there are specific
### groups of gems that depend on each other.   In that situation, put them
### alphabetically by the primary gem, followed by the dependency gems.

# Session Store
gem 'activerecord-session_store'

# JSON Model Serialization
# TODO: Investigate this gems usage, may have been replaced by Representers.
gem 'active_model_serializers', '~> 0.9.3'

...
```

DB Migration:
```
class AddSessionsTable < ActiveRecord::Migration[5.2]
  def change
    create_table :sessions do |t|
      t.string :session_id, :null => false
      t.text :data
      t.timestamps
    end

    add_index :sessions, :session_id, :unique => true
    add_index :sessions, :updated_at
  end
end
```

config/initializers/session_store.rb
```
# Be sure to restart your server when you modify this file.

session_key     = "_wowzacloud_session"
session_length  = (Settings.try(:application).try(:session).try(:max_length) || 1).to_i
# Rails.application.config.session_store :cookie_store, key: session_key, expire_after: session_length
Rails.application.config.session_store :active_record_store, key: session_key, expire_after: session_length
```

**Comment by jocko-wowza** [comment]
NVM - Found the issue.  We had a configuration in our app somewhere else that was specifically looking to insert middleware after the CookieStore.
