### ISSUE TITLE
uninitialized constant ActionDispatch::Session::AbstractSecureStore

### ISSUE THREAD

**Issue by map7** [rails/activerecord-session_store#184]
I'm upgrading an old Rails 5.2.5 app to 6.0.0 and I'm getting the following error;

`10:58:12 rails.1  | started with pid 27598
10:58:12 worker.1 | started with pid 27599
10:58:12 rails.1  | Puma starting in single mode...
10:58:12 rails.1  | * Puma version: 5.2.2 (ruby 2.6.6-p146) ("Fettisdagsbulle")
10:58:12 rails.1  | *  Min threads: 5
10:58:12 rails.1  | *  Max threads: 5
10:58:12 rails.1  | *  Environment: development
10:58:12 rails.1  | *          PID: 27600
10:58:13 rails.1  | ! Unable to load application: NameError: uninitialized constant ActionDispatch::Session::AbstractSecureStore
10:58:13 rails.1  | bundler: failed to load command: puma (/usr/local/rbenv/versions/2.6.6/bin/puma)
10:58:13 rails.1  | NameError: uninitialized constant ActionDispatch::Session::AbstractSecureStore
10:58:13 rails.1  |   /usr/local/rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/activerecord-session_store-2.0.0/lib/action_dispatch/session/active_record_store.rb:55:in `<module:Session>'
10:58:13 rails.1  |   /usr/local/rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/activerecord-session_store-2.0.0/lib/action_dispatch/session/active_record_store.rb:5:in `<module:ActionDispatch>'
10:58:13 rails.1  |   /usr/local/rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/activerecord-session_store-2.0.0/lib/action_dispatch/session/active_record_store.rb:4:in `<main>'
10:58:13 rails.1  |   /usr/local/rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/bootsnap-1.7.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require'
10:58:13 rails.1  |   /usr/local/rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/bootsnap-1.7.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'
10:58:13 rails.1  |   /usr/local/rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/bootsnap-1.7.3/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
10:58:13 rails.1  |   /usr/local/rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/bootsnap-1.7.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'
10:58:13 rails.1  |   /usr/local/rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/bootsnap-1.7.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:31:in `require'
10:58:13 rails.1  |   /usr/local/rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/activerecord-session_store-2.0.0/lib/active_record/session_store.rb:3:in `<main>'
10:58:13 rails.1  |   /usr/local/rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/bootsnap-1.7.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require'
10:58:13 rails.1  |   /usr/local/rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/bootsnap-1.7.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'
10:58:13 rails.1  |   /usr/local/rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/bootsnap-1.7.3/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
10:58:13 rails.1  |   /usr/local/rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/bootsnap-1.7.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'
10:58:13 rails.1  |   /usr/local/rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/bootsnap-1.7.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:31:in `require'
10:58:13 rails.1  |   /usr/local/rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/activerecord-session_store-2.0.0/lib/activerecord/session_store.rb:1:in `<main>'
10:58:13 rails.1  |   /usr/local/rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/bootsnap-1.7.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require'
10:58:13 rails.1  |   /usr/local/rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/bootsnap-1.7.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'
10:58:13 rails.1  |   /usr/local/rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/bootsnap-1.7.3/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
10:58:13 rails.1  |   /usr/local/rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/bootsnap-1.7.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'
10:58:13 rails.1  |   /usr/local/rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/bootsnap-1.7.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:31:in `require'
10:58:13 rails.1  |   /usr/local/rbenv/versions/2.6.6/lib/ruby/2.6.0/bundler/runtime.rb:95:in `rescue in block in require'
10:58:13 rails.1  |   /usr/local/rbenv/versions/2.6.6/lib/ruby/2.6.0/bundler/runtime.rb:72:in `block in require'
10:58:13 rails.1  |   /usr/local/rbenv/versions/2.6.6/lib/ruby/2.6.0/bundler/runtime.rb:65:in `each'
10:58:13 rails.1  |   /usr/local/rbenv/versions/2.6.6/lib/ruby/2.6.0/bundler/runtime.rb:65:in `require'
10:58:13 rails.1  |   /usr/local/rbenv/versions/2.6.6/lib/ruby/2.6.0/bundler.rb:114:in `require'
10:58:13 rails.1  |   /home/map7/code/pais/config/application.rb:9:in `<top (required)>'
10:58:13 rails.1  |   /home/map7/code/pais/config/environment.rb:2:in `require_relative'
10:58:13 rails.1  |   /home/map7/code/pais/config/environment.rb:2:in `<top (required)>'
10:58:13 rails.1  |   config.ru:3:in `require'
10:58:13 rails.1  |   config.ru:3:in `block in <main>'
10:58:13 rails.1  |   /usr/local/rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/rack-2.2.3/lib/rack/builder.rb:116:in `eval'
10:58:13 rails.1  |   /usr/local/rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/rack-2.2.3/lib/rack/builder.rb:116:in `new_from_string'
10:58:13 rails.1  |   /usr/local/rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/rack-2.2.3/lib/rack/builder.rb:105:in `load_file'
10:58:13 rails.1  |   /usr/local/rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/rack-2.2.3/lib/rack/builder.rb:66:in `parse_file'
10:58:13 rails.1  |   /usr/local/rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/puma-5.2.2/lib/puma/configuration.rb:344:in `load_rackup'
10:58:13 rails.1  |   /usr/local/rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/puma-5.2.2/lib/puma/configuration.rb:266:in `app'
10:58:13 rails.1  |   /usr/local/rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/puma-5.2.2/lib/puma/runner.rb:143:in `load_and_bind'
10:58:13 rails.1  |   /usr/local/rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/puma-5.2.2/lib/puma/single.rb:44:in `run'
10:58:13 rails.1  |   /usr/local/rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/puma-5.2.2/lib/puma/launcher.rb:181:in `run'
10:58:13 rails.1  |   /usr/local/rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/puma-5.2.2/lib/puma/cli.rb:80:in `run'
10:58:13 rails.1  |   /usr/local/rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/puma-5.2.2/bin/puma:10:in `<top (required)>'
10:58:13 rails.1  |   /usr/local/rbenv/versions/2.6.6/bin/puma:23:in `load'
10:58:13 rails.1  |   /usr/local/rbenv/versions/2.6.6/bin/puma:23:in `<top (required)>'
10:58:14 rails.1  | exited with code 1
10:58:14 system   | sending SIGTERM to all processes
10:58:14 worker.1 | terminated by SIGTERM
`

**Comment by MyrkaLarios** [comment]
Did you find a solution?

**Comment by map7** [comment]
I ended up removing this gem, then upgrading again.

**Comment by Anandshr** [comment]
I am facing same issue what version needs to be use ?

**Comment by roberthopman** [comment]
What worked for me: Remove the gem, `rails app:update`, `bundle update`, add the gem again, `bundle install`
