### ISSUE TITLE
Rails 7 TypeError in Controllers

### ISSUE THREAD

**Issue by Viacheslav1997** [rails/activerecord-session_store#218]
Hi!

Have an error in
```
def self.dump(value)
  ::Base64.encode64(Marshal.dump(value))
end
```
```
[activerecord-session_store (2.1.0) lib/active_record/session_store.rb:58:in `dump'](http://localhost:3000/admin/entities#)
[activerecord-session_store (2.1.0) lib/active_record/session_store.rb:58:in `dump'](http://localhost:3000/admin/entities#)
[activerecord-session_store (2.1.0) lib/active_record/session_store.rb:15:in `serialize'](http://localhost:3000/admin/entities#)
[activerecord-session_store (2.1.0) lib/active_record/session_store/session.rb:100:in `serialize_data!'](http://localhost:3000/admin/entities#)
[activesupport (7.0.8.4) lib/active_support/callbacks.rb:400:in `block in make_lambda'](http://localhost:3000/admin/entities#)
[activesupport (7.0.8.4) lib/active_support/callbacks.rb:199:in `block (2 levels) in halting'](http://localhost:3000/admin/entities#)
[activesupport (7.0.8.4) lib/active_support/callbacks.rb:687:in `block (2 levels) in default_terminator'](http://localhost:3000/admin/entities#)
[activesupport (7.0.8.4) lib/active_support/callbacks.rb:686:in `catch'](http://localhost:3000/admin/entities#)
[activesupport (7.0.8.4) lib/active_support/callbacks.rb:686:in `block in default_terminator'](http://localhost:3000/admin/entities#)
[activesupport (7.0.8.4) lib/active_support/callbacks.rb:200:in `block in halting'](http://localhost:3000/admin/entities#)
[activesupport (7.0.8.4) lib/active_support/callbacks.rb:595:in `block in invoke_before'](http://localhost:3000/admin/entities#)
[activesupport (7.0.8.4) lib/active_support/callbacks.rb:595:in `each'](http://localhost:3000/admin/entities#)
[activesupport (7.0.8.4) lib/active_support/callbacks.rb:595:in `invoke_before'](http://localhost:3000/admin/entities#)
[activesupport (7.0.8.4) lib/active_support/callbacks.rb:106:in `run_callbacks'](http://localhost:3000/admin/entities#)
[activesupport (7.0.8.4) lib/active_support/callbacks.rb:929:in `_run_save_callbacks'](http://localhost:3000/admin/entities#)
[activerecord (7.0.8.4) lib/active_record/callbacks.rb:455:in `create_or_update'](http://localhost:3000/admin/entities#)
[activerecord (7.0.8.4) lib/active_record/timestamp.rb:126:in `create_or_update'](http://localhost:3000/admin/entities#)
[activerecord (7.0.8.4) lib/active_record/persistence.rb:615:in `save'](http://localhost:3000/admin/entities#)
[activerecord (7.0.8.4) lib/active_record/validations.rb:47:in `save'](http://localhost:3000/admin/entities#)
[activerecord (7.0.8.4) lib/active_record/transactions.rb:298:in `block in save'](http://localhost:3000/admin/entities#)
[activerecord (7.0.8.4) lib/active_record/transactions.rb:354:in `block in with_transaction_returning_status'](http://localhost:3000/admin/entities#)
[activerecord (7.0.8.4) lib/active_record/connection_adapters/abstract/transaction.rb:319:in `block in within_new_transaction'](http://localhost:3000/admin/entities#)
```

After updating to Rails 7.0

What could be wrong?

**Comment by Viacheslav1997** [comment]
> [@Viacheslav1997](https://github.com/Viacheslav1997) did you ever find a solution to this? I'm experiencing the same error

I suppose, that adding this line helped, but i'm not sure (Don't forget to clear your browser session after wrong key generator using)
```ruby
# config/application.rb

# The default digest class for the key generator is changing from SHA1 to SHA256 in Rails 7
config.active_support.key_generator_hash_digest_class = OpenSSL::Digest::SHA1
```

**Comment by richardrails** [comment]
`
  after_action :ensure_session_is_serializable  

def ensure_session_is_serializable
    data = session.to_hash
    Marshal.dump(data)
  rescue TypeError
    sanitized = sanitize_for_session(data)
    session.clear
    sanitized.each { |k, v| session[k] = v }
  end

  def sanitize_for_session(value)
    case value
    when Hash
      value.each_with_object({}) do |(k, v), acc|
        sanitized_v = sanitize_for_session(v)
        acc[k] = sanitized_v unless sanitized_v.nil?
      end
    when Array
      value.map { |v| sanitize_for_session(v) }.compact
    else
      return nil if value.is_a?(IO)
      return nil if defined?(Tempfile) && value.is_a?(Tempfile)
      return nil if defined?(ActionDispatch::Http::UploadedFile) && value.is_a?(ActionDispatch::Http::UploadedFile)

      begin
        Marshal.dump(value)
        value
      rescue TypeError
        nil
      end
    end
  end

`
