### ISSUE TITLE
RuntimeError: rescue in session_store

### ISSUE THREAD

**Issue by aslam** [rails/activerecord-session_store#23]
I am in the process of upgrading my app from rails v 3.2.15 to 4.0.4. The app is crashing throwing the following error even though I am having activerecord-session_store gem in the Gemfile:

```
/home/aslam/.rvm/gems/ruby-2.1.0@awesome/gems/railties-4.0.4/lib/rails/application/configuration.rb:140:in `rescue in session_store': `ActiveRecord::SessionStore` is extracted out of Rails into a gem. Please add `activerecord-session_store` to your Gemfile to use it. (RuntimeError)
  from /home/aslam/.rvm/gems/ruby-2.1.0@awesome/gems/railties-4.0.4/lib/rails/application/configuration.rb:137:in `session_store'
  from /home/aslam/.rvm/gems/ruby-2.1.0@awesome/gems/railties-4.0.4/lib/rails/application.rb:345:in `block in default_middleware_stack'
  from /home/aslam/.rvm/gems/ruby-2.1.0@awesome/gems/railties-4.0.4/lib/rails/application.rb:309:in `tap'
  from /home/aslam/.rvm/gems/ruby-2.1.0@awesome/gems/railties-4.0.4/lib/rails/application.rb:309:in `default_middleware_stack'
  from /home/aslam/.rvm/gems/ruby-2.1.0@awesome/gems/railties-4.0.4/lib/rails/engine.rb:494:in `app'
  from /home/aslam/.rvm/gems/ruby-2.1.0@awesome/gems/railties-4.0.4/lib/rails/application/finisher.rb:34:in `block in <module:Finisher>'
  from /home/aslam/.rvm/gems/ruby-2.1.0@awesome/gems/railties-4.0.4/lib/rails/initializable.rb:30:in `instance_exec'
  from /home/aslam/.rvm/gems/ruby-2.1.0@awesome/gems/railties-4.0.4/lib/rails/initializable.rb:30:in `run'
  from /home/aslam/.rvm/gems/ruby-2.1.0@awesome/gems/railties-4.0.4/lib/rails/initializable.rb:55:in `block in run_initializers'
  from /home/aslam/.rvm/rubies/ruby-2.1.0/lib/ruby/2.1.0/tsort.rb:226:in `block in tsort_each'
  from /home/aslam/.rvm/rubies/ruby-2.1.0/lib/ruby/2.1.0/tsort.rb:348:in `block (2 levels) in each_strongly_connected_component'
  from /home/aslam/.rvm/rubies/ruby-2.1.0/lib/ruby/2.1.0/tsort.rb:427:in `each_strongly_connected_component_from'
  from /home/aslam/.rvm/rubies/ruby-2.1.0/lib/ruby/2.1.0/tsort.rb:347:in `block in each_strongly_connected_component'
  from /home/aslam/.rvm/rubies/ruby-2.1.0/lib/ruby/2.1.0/tsort.rb:345:in `each'
  from /home/aslam/.rvm/rubies/ruby-2.1.0/lib/ruby/2.1.0/tsort.rb:345:in `call'
  from /home/aslam/.rvm/rubies/ruby-2.1.0/lib/ruby/2.1.0/tsort.rb:345:in `each_strongly_connected_component'
  from /home/aslam/.rvm/rubies/ruby-2.1.0/lib/ruby/2.1.0/tsort.rb:224:in `tsort_each'
  from /home/aslam/.rvm/rubies/ruby-2.1.0/lib/ruby/2.1.0/tsort.rb:205:in `tsort_each'
  from /home/aslam/.rvm/gems/ruby-2.1.0@awesome/gems/railties-4.0.4/lib/rails/initializable.rb:54:in `run_initializers'
  from /home/aslam/.rvm/gems/ruby-2.1.0@awesome/gems/railties-4.0.4/lib/rails/application.rb:215:in `initialize!'
  from /home/aslam/.rvm/gems/ruby-2.1.0@awesome/gems/railties-4.0.4/lib/rails/railtie/configurable.rb:30:in `method_missing'
  from /home/aslam/work/projects/awesome/config/environment.rb:5:in `<top (required)>'
  from /home/aslam/work/projects/awesome/config.ru:3:in `require'
  from /home/aslam/work/projects/awesome/config.ru:3:in `block in <main>'
  from /home/aslam/.rvm/gems/ruby-2.1.0@awesome/gems/rack-1.5.2/lib/rack/builder.rb:55:in `instance_eval'
  from /home/aslam/.rvm/gems/ruby-2.1.0@awesome/gems/rack-1.5.2/lib/rack/builder.rb:55:in `initialize'
  from /home/aslam/work/projects/awesome/config.ru:in `new'
  from /home/aslam/work/projects/awesome/config.ru:in `<main>'
  from /home/aslam/.rvm/gems/ruby-2.1.0@awesome/gems/rack-1.5.2/lib/rack/builder.rb:49:in `eval'
  from /home/aslam/.rvm/gems/ruby-2.1.0@awesome/gems/rack-1.5.2/lib/rack/builder.rb:49:in `new_from_string'
  from /home/aslam/.rvm/gems/ruby-2.1.0@awesome/gems/rack-1.5.2/lib/rack/builder.rb:40:in `parse_file'
  from /home/aslam/.rvm/gems/ruby-2.1.0@awesome/gems/rack-1.5.2/lib/rack/server.rb:277:in `build_app_and_options_from_config'
  from /home/aslam/.rvm/gems/ruby-2.1.0@awesome/gems/rack-1.5.2/lib/rack/server.rb:199:in `app'
  from /home/aslam/.rvm/gems/ruby-2.1.0@awesome/gems/railties-4.0.4/lib/rails/commands/server.rb:48:in `app'
  from /home/aslam/.rvm/gems/ruby-2.1.0@awesome/gems/rack-1.5.2/lib/rack/server.rb:314:in `wrapped_app'
  from /home/aslam/.rvm/gems/ruby-2.1.0@awesome/gems/railties-4.0.4/lib/rails/commands/server.rb:75:in `start'
  from /home/aslam/.rvm/gems/ruby-2.1.0@awesome/gems/railties-4.0.4/lib/rails/commands.rb:76:in `block in <top (required)>'
  from /home/aslam/.rvm/gems/ruby-2.1.0@awesome/gems/railties-4.0.4/lib/rails/commands.rb:71:in `tap'
  from /home/aslam/.rvm/gems/ruby-2.1.0@awesome/gems/railties-4.0.4/lib/rails/commands.rb:71:in `<top (required)>'
  from bin/rails:4:in `require'
  from bin/rails:4:in `<main>'
```
I am using Bundler 1.5.3

```
$> bundle show activerecord-session_store
/home/aslam/.rvm/gems/ruby-2.1.0@awesome/gems/activerecord-session_store-0.1.0
```

**Comment by sikachu** [comment]
Closing this due to inactivity. If you have more information, please post here so I can reopen the ticket.
