### ISSUE TITLE
comparison of Fixnum with nil failed

### ISSUE THREAD

**Issue by hemashree** [rails/activerecord-session_store#45]
Hi,

I am getting this error "Unexpected error while processing request: comparison of Fixnum with nil faile"
when I try to do  any actions like rake db:create, rake db:migrate and rails s in my mac os yosemite. This is the log

```
 hemas-MacBook-Pro:inotary hemashree$ rake db:migrate
rake aborted!
ArgumentError: comparison of Fixnum with nil failed
/Users/hemashree/.bundler/ruby/2.0.0/activerecord-session_store-2d9517d0f262/lib/active_record/session_store/extension/logger_silencer.rb:34:in `<'
/Users/hemashree/.bundler/ruby/2.0.0/activerecord-session_store-2d9517d0f262/lib/active_record/session_store/extension/logger_silencer.rb:34:in `add_with_threadsafety'
/Library/Ruby/Gems/2.0.0/gems/activerecord-4.0.1/lib/active_record/connection_adapters/abstract_adapter.rb:438:in `rescue in log'
/Library/Ruby/Gems/2.0.0/gems/activerecord-4.0.1/lib/active_record/connection_adapters/abstract_adapter.rb:435:in `log'
/Library/Ruby/Gems/2.0.0/gems/activerecord-4.0.1/lib/active_record/connection_adapters/postgresql/database_statements.rb:137:in `exec_query'
/Library/Ruby/Gems/2.0.0/gems/activerecord-4.0.1/lib/active_record/connection_adapters/postgresql_adapter.rb:891:in `select'
/Library/Ruby/Gems/2.0.0/gems/activerecord-4.0.1/lib/active_record/connection_adapters/abstract/database_statements.rb:24:in `select_all'
/Library/Ruby/Gems/2.0.0/gems/activerecord-4.0.1/lib/active_record/connection_adapters/abstract/query_cache.rb:63:in `select_all'
/Library/Ruby/Gems/2.0.0/gems/activerecord-4.0.1/lib/active_record/querying.rb:36:in `find_by_sql'
/Library/Ruby/Gems/2.0.0/gems/activerecord-4.0.1/lib/active_record/relation.rb:585:in `exec_queries'
/Library/Ruby/Gems/2.0.0/gems/activerecord-4.0.1/lib/active_record/relation.rb:471:in `load'
/Library/Ruby/Gems/2.0.0/gems/activerecord-4.0.1/lib/active_record/relation.rb:220:in `to_a'
/Library/Ruby/Gems/2.0.0/gems/activerecord-4.0.1/lib/active_record/relation/delegation.rb:12:in `map'
/Library/Ruby/Gems/2.0.0/gems/activerecord-4.0.1/lib/active_record/migration.rb:787:in `get_all_versions'
/Library/Ruby/Gems/2.0.0/gems/activerecord-4.0.1/lib/active_record/migration.rb:949:in `migrated'
/Library/Ruby/Gems/2.0.0/gems/activerecord-4.0.1/lib/active_record/migration.rb:954:in `ran?'
/Library/Ruby/Gems/2.0.0/gems/activerecord-4.0.1/lib/active_record/migration.rb:931:in `block in runnable'
/Library/Ruby/Gems/2.0.0/gems/activerecord-4.0.1/lib/active_record/migration.rb:931:in `reject'
/Library/Ruby/Gems/2.0.0/gems/activerecord-4.0.1/lib/active_record/migration.rb:931:in `runnable'
/Library/Ruby/Gems/2.0.0/gems/activerecord-4.0.1/lib/active_record/migration.rb:908:in `migrate'
/Library/Ruby/Gems/2.0.0/gems/activerecord-4.0.1/lib/active_record/migration.rb:764:in `up'
/Library/Ruby/Gems/2.0.0/gems/activer
```

please find this and give me the solution.

**Comment by sikachu** [comment]
I'm going to close this issue due to inactivity. Please let me know and providing more log if you still having this issue.
