### ISSUE TITLE
undefined method `silence_logger' for Logging::Logger

### ISSUE THREAD

**Issue by wbotelhos** [rails/activerecord-session_store#74]
Hi,

I'm using `logging 2.0.0` and i have the following error:

```ruby
silence_logger' for <Logging::Logger:0x3fc0dba74b54 name="ActiveRecord::Base">:Logging::Logger' duration=1.58 view=0.00 db=0.00
[2016-02-28T13:02:49] FATAL Rails : 
NoMethodError (undefined method `silence_logger' for <Logging::Logger:0x3fc0dba74b54 name="ActiveRecord::Base">:Logging::Logger):
  activerecord-session_store (0.1.2) lib/action_dispatch/session/active_record_store.rb:65:in `get_session'
  rack (1.6.4) lib/rack/session/abstract/id.rb:266:in `load_session'
  actionpack (4.2.5.1) lib/action_dispatch/middleware/session/abstract_store.rb:43:in `block in load_session'
  actionpack (4.2.5.1) lib/action_dispatch/middleware/session/abstract_store.rb:51:in `stale_session_check!'
  actionpack (4.2.5.1) lib/action_dispatch/middleware/session/abstract_store.rb:43:in `load_session'
  actionpack (4.2.5.1) lib/action_dispatch/request/session.rb:180:in `load!'
  actionpack (4.2.5.1) lib/action_dispatch/request/session.rb:172:in `load_for_read!'
  actionpack (4.2.5.1) lib/action_dispatch/request/session.rb:89:in `[]'
  warden (1.2.6) lib/warden/session_serializer.rb:30:in `fetch'
  warden (1.2.6) lib/warden/proxy.rb:212:in `user'
  warden (1.2.6) lib/warden/proxy.rb:322:in `_perform_authentication'
  warden (1.2.6) lib/warden/proxy.rb:104:in `authenticate'
  devise (3.5.6) lib/devise/controllers/helpers.rb:124:in `current_user'
  paper_trail (4.1.0) lib/paper_trail/frameworks/rails/controller.rb:35:in `rescue in user_for_paper_trail'
  paper_trail (4.1.0) lib/paper_trail/frameworks/rails/controller.rb:32:in `user_for_paper_trail'
  paper_trail (4.1.0) lib/paper_trail/frameworks/rails/controller.rb:79:in `set_paper_trail_whodunnit'
  activesupport (4.2.5.1) lib/active_support/callbacks.rb:432:in `block in make_lambda'
  activesupport (4.2.5.1) lib/active_support/callbacks.rb:164:in `call'
  activesupport (4.2.5.1) lib/active_support/callbacks.rb:164:in `block in halting'
  activesupport (4.2.5.1) lib/active_support/callbacks.rb:504:in `call'
  activesupport (4.2.5.1) lib/active_support/callbacks.rb:504:in `block in call'
  activesupport (4.2.5.1) lib/active_support/callbacks.rb:504:in `each'
  activesupport (4.2.5.1) lib/active_support/callbacks.rb:504:in `call'
  activesupport (4.2.5.1) lib/active_support/callbacks.rb:92:in `__run_callbacks__'
  activesupport (4.2.5.1) lib/active_support/callbacks.rb:778:in `_run_process_action_callbacks'
  activesupport (4.2.5.1) lib/active_support/callbacks.rb:81:in `run_callbacks'
  actionpack (4.2.5.1) lib/abstract_controller/callbacks.rb:19:in `process_action'
  actionpack (4.2.5.1) lib/action_controller/metal/rescue.rb:29:in `process_action'
  actionpack (4.2.5.1) lib/action_controller/metal/instrumentation.rb:32:in `block in process_action'
  activesupport (4.2.5.1) lib/active_support/notifications.rb:164:in `block in instrument'
  activesupport (4.2.5.1) lib/active_support/notifications/instrumenter.rb:20:in `instrument'
  activesupport (4.2.5.1) lib/active_support/notifications.rb:164:in `instrument'
  actionpack (4.2.5.1) lib/action_controller/metal/instrumentation.rb:30:in `process_action'
  actionpack (4.2.5.1) lib/action_controller/metal/params_wrapper.rb:250:in `process_action'
  activerecord (4.2.5.1) lib/active_record/railties/controller_runtime.rb:18:in `process_action'
  actionpack (4.2.5.1) lib/abstract_controller/base.rb:137:in `process'
  actionview (4.2.5.1) lib/action_view/rendering.rb:30:in `process'
  actionpack (4.2.5.1) lib/action_controller/metal.rb:196:in `dispatch'
  actionpack (4.2.5.1) lib/action_controller/metal/rack_delegation.rb:13:in `dispatch'
  actionpack (4.2.5.1) lib/action_controller/metal.rb:237:in `block in action'
  actionpack (4.2.5.1) lib/action_dispatch/routing/route_set.rb:74:in `call'
  actionpack (4.2.5.1) lib/action_dispatch/routing/route_set.rb:74:in `dispatch'
  actionpack (4.2.5.1) lib/action_dispatch/routing/route_set.rb:43:in `serve'
  actionpack (4.2.5.1) lib/action_dispatch/journey/router.rb:43:in `block in serve'
  actionpack (4.2.5.1) lib/action_dispatch/journey/router.rb:30:in `each'
  actionpack (4.2.5.1) lib/action_dispatch/journey/router.rb:30:in `serve'
  actionpack (4.2.5.1) lib/action_dispatch/routing/route_set.rb:815:in `call'
  bullet (5.0.0) lib/bullet/rack.rb:12:in `call'
  i18n-js (2.1.2) lib/i18n-js/middleware.rb:11:in `call'
  warden (1.2.6) lib/warden/manager.rb:35:in `block in call'
  warden (1.2.6) lib/warden/manager.rb:34:in `catch'
  warden (1.2.6) lib/warden/manager.rb:34:in `call'
  rack (1.6.4) lib/rack/etag.rb:24:in `call'
  rack (1.6.4) lib/rack/conditionalget.rb:25:in `call'
  rack (1.6.4) lib/rack/head.rb:13:in `call'
  actionpack (4.2.5.1) lib/action_dispatch/middleware/params_parser.rb:27:in `call'
  actionpack (4.2.5.1) lib/action_dispatch/middleware/flash.rb:260:in `call'
  rack (1.6.4) lib/rack/session/abstract/id.rb:225:in `context'
  rack (1.6.4) lib/rack/session/abstract/id.rb:220:in `call'
  actionpack (4.2.5.1) lib/action_dispatch/middleware/cookies.rb:560:in `call'
  activerecord (4.2.5.1) lib/active_record/query_cache.rb:36:in `call'
  activerecord (4.2.5.1) lib/active_record/connection_adapters/abstract/connection_pool.rb:653:in `call'
  activerecord (4.2.5.1) lib/active_record/migration.rb:377:in `call'
  actionpack (4.2.5.1) lib/action_dispatch/middleware/callbacks.rb:29:in `block in call'
  activesupport (4.2.5.1) lib/active_support/callbacks.rb:88:in `__run_callbacks__'
  activesupport (4.2.5.1) lib/active_support/callbacks.rb:778:in `_run_call_callbacks'
  activesupport (4.2.5.1) lib/active_support/callbacks.rb:81:in `run_callbacks'
  actionpack (4.2.5.1) lib/action_dispatch/middleware/callbacks.rb:27:in `call'
  actionpack (4.2.5.1) lib/action_dispatch/middleware/reloader.rb:73:in `call'
  actionpack (4.2.5.1) lib/action_dispatch/middleware/remote_ip.rb:78:in `call'
  actionpack (4.2.5.1) lib/action_dispatch/middleware/debug_exceptions.rb:17:in `call'
  actionpack (4.2.5.1) lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
  lograge (0.3.6) lib/lograge/rails_ext/rack/logger.rb:15:in `call_app'
  railties (4.2.5.1) lib/rails/rack/logger.rb:22:in `call'
  quiet_assets (1.1.0) lib/quiet_assets.rb:27:in `call_with_quiet_assets'
  request_store (1.3.0) lib/request_store/middleware.rb:9:in `call'
  actionpack (4.2.5.1) lib/action_dispatch/middleware/request_id.rb:21:in `call'
  rack (1.6.4) lib/rack/methodoverride.rb:22:in `call'
  rack (1.6.4) lib/rack/runtime.rb:18:in `call'
  activesupport (4.2.5.1) lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
  rack (1.6.4) lib/rack/lock.rb:17:in `call'
  actionpack (4.2.5.1) lib/action_dispatch/middleware/static.rb:116:in `call'
  rack (1.6.4) lib/rack/sendfile.rb:113:in `call'
  railties (4.2.5.1) lib/rails/engine.rb:518:in `call'
  railties (4.2.5.1) lib/rails/application.rb:165:in `call'
  rack (1.6.4) lib/rack/content_length.rb:15:in `call'
  thin (1.6.4) lib/thin/connection.rb:86:in `block in pre_process'
  thin (1.6.4) lib/thin/connection.rb:84:in `catch'
  thin (1.6.4) lib/thin/connection.rb:84:in `pre_process'
  thin (1.6.4) lib/thin/connection.rb:53:in `process'
  thin (1.6.4) lib/thin/connection.rb:39:in `receive_data'
  eventmachine (1.0.9.1) lib/eventmachine.rb:193:in `run_machine'
  eventmachine (1.0.9.1) lib/eventmachine.rb:193:in `run'
  thin (1.6.4) lib/thin/backends/base.rb:73:in `start'
  thin (1.6.4) lib/thin/server.rb:162:in `start'
  rack (1.6.4) lib/rack/handler/thin.rb:19:in `run'
  rack (1.6.4) lib/rack/server.rb:286:in `start'
  railties (4.2.5.1) lib/rails/commands/server.rb:80:in `start'
  railties (4.2.5.1) lib/rails/commands/commands_tasks.rb:80:in `block in server'
  railties (4.2.5.1) lib/rails/commands/commands_tasks.rb:75:in `tap'
  railties (4.2.5.1) lib/rails/commands/commands_tasks.rb:75:in `server'
  railties (4.2.5.1) lib/rails/commands/commands_tasks.rb:39:in `run_command!'
  railties (4.2.5.1) lib/rails/commands.rb:17:in `<top (required)>'
  bin/rails:9:in `require'
  bin/rails:9:in `<top (required)>'
  spring (1.6.4) lib/spring/client/rails.rb:28:in `load'
  spring (1.6.4) lib/spring/client/rails.rb:28:in `call'
  spring (1.6.4) lib/spring/client/command.rb:7:in `call'
  spring (1.6.4) lib/spring/client.rb:28:in `run'
  spring (1.6.4) bin/spring:49:in `<top (required)>'
  spring (1.6.4) lib/spring/binstub.rb:11:in `load'
  spring (1.6.4) lib/spring/binstub.rb:11:in `<top (required)>'
  bin/spring:13:in `require'
  bin/spring:13:in `<top (required)>'
  bin/rails:3:in `load'
  bin/rails:3:in `<main>'
```

It comes from: https://github.com/rails/activerecord-session_store/blob/1cc0daf77d542045da4f6a43cba9ce04c27453dd/lib/active_record/session_store.rb#L37

What it can be?

**Comment by sikachu** [comment]
Have you include the module per the description in the README?

```Please note that you will need to manually include the silencer module to your custom logger if you are using a logger other than Logger and Syslog::Logger and their subclasses:

    MyLogger.send :include, ActiveRecord::SessionStore::Extension::LoggerSilencer

This silencer is being used to silence the logger and not leaking private information into the log, and it is required for security reason.```

**Comment by wbotelhos** [comment]
Thank you, @sikachu . I did not pay attention.
I solve with the following code:

```
Logging.logger.send :include, ActiveRecord::SessionStore::Extension::LoggerSilencer
```

Any difference from `.send` our directly `.include` in this case?

**Comment by sikachu** [comment]
@wbotelhos glad that fixed it!

It could be the case that logger object was already instantiated before it evaluates your `include` line. By doing `send :include`, it include the module into your logger object directly, making the method available on that object.

I'm going to close this issue. Please let me know if you run into anything else.

**Comment by ngollan** [comment]
Is `#silence_logger` in any way, shape, or form different from the functionality offered by `#silence` in `ActiveSupport::LoggerSilence`? It would arguably make more sense to use more prominent  Rails ecosystem functionality than requiring "standard" loggers to be extended with even more obscure NIH methods.

https://github.com/rails/rails/blob/2518bda97cbbcb33dc9a92e70d5b01c09e64d12d/activesupport/lib/active_support/logger_silence.rb#L14
