### ISSUE TITLE
LoggerSilencer fails by comparing incorrect log_level

### ISSUE THREAD

**Issue by bfbones** [rails/activerecord-session_store#87]
Hello,

my unicorn is sometimes serving a blank page, because the logger silencer of ar-session_store 1.0.0 just fails by comparing incorrect log levels. It seems that sometimes there are wrong data types, such as fixnum being compared with a symbol.
I am using this application.rb for my rails app:

```
config.logger = Logger.new("#{Rails.root}/log/app.log")
config.log_level = :warn
```

Sometimes, after several requests this happens to my app:

```
E, [2016-09-02T09:23:12.990343 #21845] ERROR -- : app error: comparison of Fixnum with :debug failed (ArgumentError)
E, [2016-09-02T09:23:12.990421 #21845] ERROR -- : /usr/local/rvm/gems/ruby-2.2.2/gems/activerecord-session_store-1.0.0/lib/active_record/session_store/extension/logger_silencer.rb:35:in `<'
E, [2016-09-02T09:23:12.990463 #21845] ERROR -- : /usr/local/rvm/gems/ruby-2.2.2/gems/activerecord-session_store-1.0.0/lib/active_record/session_store/extension/logger_silencer.rb:35:in `add_with_threadsafety'  E, [2016-09-02T09:23:12.990500 #21845] ERROR -- : /usr/local/rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/logger.rb:434:in `info'
E, [2016-09-02T09:23:12.990534 #21845] ERROR -- : /usr/local/rvm/gems/ruby-2.2.2/gems/rack-timeout-0.4.2/lib/rack/timeout/logging-observer.rb:42:in `log_state_change'
E, [2016-09-02T09:23:12.990568 #21845] ERROR -- : /usr/local/rvm/gems/ruby-2.2.2/gems/rack-timeout-0.4.2/lib/rack/timeout/core.rb:190:in `call'
E, [2016-09-02T09:23:12.990602 #21845] ERROR -- : /usr/local/rvm/gems/ruby-2.2.2/gems/rack-timeout-0.4.2/lib/rack/timeout/core.rb:190:in `block in notify_state_change_observers'
E, [2016-09-02T09:23:12.990635 #21845] ERROR -- : /usr/local/rvm/gems/ruby-2.2.2/gems/rack-timeout-0.4.2/lib/rack/timeout/core.rb:190:in `each'
E, [2016-09-02T09:23:12.990668 #21845] ERROR -- : /usr/local/rvm/gems/ruby-2.2.2/gems/rack-timeout-0.4.2/lib/rack/timeout/core.rb:190:in `notify_state_change_observers'
E, [2016-09-02T09:23:12.990701 #21845] ERROR -- : /usr/local/rvm/gems/ruby-2.2.2/gems/rack-timeout-0.4.2/lib/rack/timeout/core.rb:167:in `_set_state!'
E, [2016-09-02T09:23:12.990734 #21845] ERROR -- : /usr/local/rvm/gems/ruby-2.2.2/gems/rack-timeout-0.4.2/lib/rack/timeout/core.rb:106:in `call'
E, [2016-09-02T09:23:12.990791 #21845] ERROR -- : /usr/local/rvm/gems/ruby-2.2.2/gems/activesupport-4.2.5.2/lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
E, [2016-09-02T09:23:12.990827 #21845] ERROR -- : /usr/local/rvm/gems/ruby-2.2.2/gems/actionpack-4.2.5.2/lib/action_dispatch/middleware/static.rb:116:in `call'
E, [2016-09-02T09:23:12.990861 #21845] ERROR -- : /usr/local/rvm/gems/ruby-2.2.2/gems/rack-1.6.4/lib/rack/sendfile.rb:113:in `call'
E, [2016-09-02T09:23:12.990893 #21845] ERROR -- : /usr/local/rvm/gems/ruby-2.2.2/gems/railties-4.2.5.2/lib/rails/engine.rb:518:in `call'
E, [2016-09-02T09:23:12.990925 #21845] ERROR -- : /usr/local/rvm/gems/ruby-2.2.2/gems/railties-4.2.5.2/lib/rails/application.rb:165:in `call'
E, [2016-09-02T09:23:12.990958 #21845] ERROR -- : /usr/local/rvm/gems/ruby-2.2.2/gems/railties-4.2.5.2/lib/rails/railtie.rb:194:in `public_send'
E, [2016-09-02T09:23:12.991028 #21845] ERROR -- : /usr/local/rvm/gems/ruby-2.2.2/gems/railties-4.2.5.2/lib/rails/railtie.rb:194:in `method_missing'
E, [2016-09-02T09:23:12.991064 #21845] ERROR -- : /usr/local/rvm/gems/ruby-2.2.2/gems/unicorn-5.1.0/lib/unicorn/http_server.rb:562:in `process_client'
E, [2016-09-02T09:23:12.991096 #21845] ERROR -- : /usr/local/rvm/gems/ruby-2.2.2/gems/unicorn-5.1.0/lib/unicorn/http_server.rb:658:in `worker_loop'
E, [2016-09-02T09:23:12.991128 #21845] ERROR -- : /usr/local/rvm/gems/ruby-2.2.2/gems/unicorn-5.1.0/lib/unicorn/http_server.rb:508:in `spawn_missing_workers'
E, [2016-09-02T09:23:12.991160 #21845] ERROR -- : /usr/local/rvm/gems/ruby-2.2.2/gems/unicorn-5.1.0/lib/unicorn/http_server.rb:132:in `start'
E, [2016-09-02T09:23:12.991192 #21845] ERROR -- : /usr/local/rvm/gems/ruby-2.2.2/gems/unicorn-5.1.0/bin/unicorn_rails:209:in `<top (required)>'
E, [2016-09-02T09:23:12.991224 #21845] ERROR -- : /usr/local/rvm/gems/ruby-2.2.2/bin/unicorn_rails:23:in `load'
E, [2016-09-02T09:23:12.991255 #21845] ERROR -- : /usr/local/rvm/gems/ruby-2.2.2/bin/unicorn_rails:23:in `<main>'
E, [2016-09-02T09:23:12.991286 #21845] ERROR -- : /usr/local/rvm/gems/ruby-2.2.2/bin/ruby_executable_hooks:15:in `eval'
E, [2016-09-02T09:23:12.991318 #21845] ERROR -- : /usr/local/rvm/gems/ruby-2.2.2/bin/ruby_executable_hooks:15:in `<main>'
```

I've just dirty fixed that by simply rescue'ing this, cause a simple fix checking the data types didn't cleanly solved that issue.
Looking further to see a solution here.

**Comment by vellotis** [comment]
I am facing the same problem. `comparison of Fixnum with :warn failed (ArgumentError)`

But I do not apply `:warn` anywhere in my code.

**Comment by byroot** [comment]
LoggerSilencer was removed in 2.0.0, users are now expected to use the LoggerSilence module from Active Support.

Closing.
